services:

  postgres:
    image: postgres:16
    container_name: postgres
    ports:
      - "1234:5432"
    restart: on-failure
    volumes:
      - "./db_init:/docker-entrypoint-initdb.d"
    environment:
      POSTGRES_USER:      ${PG_USER}
      POSTGRES_PASSWORD:  ${PG_PASS}
      POSTGRES_DB:        job_postings